# Generated by Django 4.2.1 on 2023-05-31 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='phobe_number',
            new_name='phone_number',
        ),
    ]
